/**
 * Migración única de localStorage → Supabase.
 *
 * Reglas de seguridad:
 * - Solo corre si el flag 'pos_migration_v1' NO está marcado como 'done'.
 * - Usa upsert con ignoreDuplicates para que sea idempotente: si se interrumpe
 *   y vuelve a correr, no duplica registros.
 * - Los datos en localStorage NO se borran (quedan como backup).
 * - Al terminar con éxito, escribe el flag para no volver a correr.
 */

import { supabase } from './supabase'

const MIGRATION_FLAG = 'pos_migration_v1'

const LS = {
  PRODUCTS:           'pos_products',
  SALES:              'pos_sales',
  EXPENSES:           'pos_expenses',
  EXPENSE_TEMPLATES:  'pos_expense_templates',
  CLIENTS:            'pos_clients',
  SALES_NOTES:        'pos_sales_notes',
  DOCUMENTS:          'pos_documents',
  SETTINGS:           'pos_settings',
}

function readLS(key) {
  try { return JSON.parse(localStorage.getItem(key) || '[]') } catch { return [] }
}

function readLSObj(key) {
  try { return JSON.parse(localStorage.getItem(key)) } catch { return null }
}

async function upsertChunked(table, rows) {
  if (!rows.length) return null
  const CHUNK = 500
  for (let i = 0; i < rows.length; i += CHUNK) {
    const { error } = await supabase
      .from(table)
      .upsert(rows.slice(i, i + CHUNK), { onConflict: 'id', ignoreDuplicates: true })
    if (error) return error
  }
  return null
}

export async function runMigrationIfNeeded() {
  if (localStorage.getItem(MIGRATION_FLAG) === 'done') return { skipped: true }

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { skipped: true, reason: 'no-auth' }

  const sid = user.id

  // Verificar si hay algo que migrar
  const hasData = Object.values(LS).some((key) => {
    try {
      const v = JSON.parse(localStorage.getItem(key))
      return Array.isArray(v) ? v.length > 0 : v !== null
    } catch { return false }
  })

  if (!hasData) {
    localStorage.setItem(MIGRATION_FLAG, 'done')
    return { skipped: true, reason: 'no-local-data' }
  }

  console.info('[migración] Iniciando migración de datos locales…')
  const errors = []

  // ── Productos ────────────────────────────────────────────────────────────
  const localProducts = readLS(LS.PRODUCTS)
  if (localProducts.length) {
    const rows = localProducts.map((p) => ({
      id:         p.id,
      store_id:   sid,
      barcode:    p.barcode,
      name:       p.name,
      variante:   p.variante    ?? null,
      marca:      p.marca       ?? null,
      proveedor:  p.proveedor   ?? null,
      category:   p.category    ?? null,
      price:      p.price       ?? 0,
      cost:       p.cost        ?? 0,
      stock:      p.stock       ?? 0,
      margen_pct: p.margenPct   ?? null,
      created_at: p.createdAt   ?? new Date().toISOString(),
    }))
    const err = await upsertChunked('products', rows)
    if (err) errors.push({ table: 'products', err })
    else console.info(`[migración] ✓ ${rows.length} productos`)
  }

  // ── Ventas ───────────────────────────────────────────────────────────────
  const localSales = readLS(LS.SALES)
  if (localSales.length) {
    const rows = localSales.map((s) => ({
      id:              s.id,
      store_id:        sid,
      date:            s.date,
      channel:         s.channel         ?? 'POS',
      items:           s.items           ?? [],
      list_total:      s.listTotal       ?? s.total ?? 0,
      discount:        s.discount        ?? 0,
      discount_amount: s.discountAmount  ?? 0,
      effective_total: s.effectiveTotal  ?? s.total ?? 0,
      payment_method:  s.paymentMethod   ?? null,
      card_commission: s.cardCommission  ?? 0,
      shipping:        s.shipping        ?? { cobro: 0, costo: 0, margin: 0 },
      status:          s.status          ?? 'COMPLETED',
      voided_at:       s.voidedAt        ?? null,
      created_at:      s.date            ?? new Date().toISOString(),
    }))
    const err = await upsertChunked('sales', rows)
    if (err) errors.push({ table: 'sales', err })
    else console.info(`[migración] ✓ ${rows.length} ventas`)
  }

  // ── Gastos ───────────────────────────────────────────────────────────────
  const localExpenses = readLS(LS.EXPENSES)
  if (localExpenses.length) {
    const rows = localExpenses.map((e) => ({
      id:             e.id,
      store_id:       sid,
      date:           e.date,
      description:    e.description,
      amount:         e.amount        ?? 0,
      subtype:        e.subtype       ?? 'General',
      doc_type:       e.docType       ?? 'boleta',
      type:           e.type          ?? 'variable',
      iva_credito:    e.ivaCredito    ?? 0,
      template_id:    e.templateId    ?? null,
      auto_generated: e.autoGenerated ?? false,
      created_at:     e.createdAt     ?? new Date().toISOString(),
    }))
    const err = await upsertChunked('expenses', rows)
    if (err) errors.push({ table: 'expenses', err })
    else console.info(`[migración] ✓ ${rows.length} gastos`)
  }

  // ── Plantillas de gasto ──────────────────────────────────────────────────
  const localTemplates = readLS(LS.EXPENSE_TEMPLATES)
  if (localTemplates.length) {
    const rows = localTemplates.map((t) => ({
      id:                 t.id,
      store_id:           sid,
      description:        t.description,
      amount:             t.amount            ?? 0,
      doc_type:           t.docType           ?? 'boleta',
      is_template:        true,
      active:             t.active            !== false,
      last_imputed_month: t.lastImputedMonth  ?? null,
      created_at:         t.createdAt         ?? new Date().toISOString(),
    }))
    const err = await upsertChunked('expense_templates', rows)
    if (err) errors.push({ table: 'expense_templates', err })
    else console.info(`[migración] ✓ ${rows.length} plantillas`)
  }

  // ── Clientes ─────────────────────────────────────────────────────────────
  const localClients = readLS(LS.CLIENTS)
  if (localClients.length) {
    const rows = localClients.map((c) => ({
      id:           c.id,
      store_id:     sid,
      razon_social: c.razonSocial,
      rut:          c.rut       ?? null,
      giro:         c.giro      ?? null,
      direccion:    c.direccion ?? null,
      comuna:       c.comuna    ?? null,
      contacto:     c.contacto  ?? null,
      telefono:     c.telefono  ?? null,
      mail:         c.mail      ?? null,
      created_at:   c.createdAt ?? new Date().toISOString(),
    }))
    const err = await upsertChunked('clients', rows)
    if (err) errors.push({ table: 'clients', err })
    else console.info(`[migración] ✓ ${rows.length} clientes`)
  }

  // ── Notas de venta ───────────────────────────────────────────────────────
  const localNotes = readLS(LS.SALES_NOTES)
  if (localNotes.length) {
    const rows = localNotes.map((n) => ({
      id:            n.id,
      store_id:      sid,
      folio:         n.folio,
      date:          n.date,
      cliente:       n.cliente       ?? null,
      items:         n.items         ?? [],
      total:         n.total         ?? 0,
      neto:          n.neto          ?? 0,
      iva:           n.iva           ?? 0,
      estado:        n.estado        ?? 'pendiente',
      oc:            n.oc            ?? null,
      observaciones: n.observaciones ?? null,
      created_at:    n.createdAt     ?? new Date().toISOString(),
    }))
    const err = await upsertChunked('sales_notes', rows)
    if (err) errors.push({ table: 'sales_notes', err })
    else console.info(`[migración] ✓ ${rows.length} notas de venta`)
  }

  // ── Documentos ───────────────────────────────────────────────────────────
  const localDocs = readLS(LS.DOCUMENTS)
  if (localDocs.length) {
    const rows = localDocs.map((d) => ({
      id:             d.id,
      store_id:       sid,
      tipo_documento: d.tipoDocumento,
      folio:          d.folio,
      fecha_emision:  d.fechaEmision ?? null,
      emisor:         d.emisor       ?? null,
      receptor:       d.receptor     ?? null,
      items:          d.items        ?? [],
      neto:           d.neto         ?? 0,
      iva:            d.iva          ?? 0,
      total:          d.total        ?? 0,
      forma_pago:     d.formaPago    ?? null,
      estado:         d.estado       ?? 'emitida',
      anulada_at:     d.anuladaAt    ?? null,
      created_at:     d.createdAt    ?? new Date().toISOString(),
    }))
    const err = await upsertChunked('documents', rows)
    if (err) errors.push({ table: 'documents', err })
    else console.info(`[migración] ✓ ${rows.length} documentos`)
  }

  if (errors.length) {
    console.error('[migración] Errores:', errors)
    // No marcar como done: la próxima carga reintentará automáticamente
    return { success: false, errors }
  }

  localStorage.setItem(MIGRATION_FLAG, 'done')
  console.info('[migración] ✓ Completada. Los datos locales se conservan como backup.')
  return { success: true }
}