import { useMemo, useState } from 'react'
import * as XLSX from 'xlsx'
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts'
import { calcAnalytics, calcInventoryCapital, formatCLP } from '../utils/calculations'

const PERIODS    = [{ key: 'today', label: 'Hoy' }, { key: 'week', label: 'Semana' }, { key: 'month', label: 'Mes' }, { key: 'all', label: 'Todo' }]
const PAY_LABELS = { cash: 'Efectivo', transfer: 'Transferencia', card: 'Tarjeta', mercadopago: 'Mercado Pago' }
const CH_LABELS  = { POS: 'Punto de Venta', ECOM: 'E-Commerce' }
const STAGNANT_THRESHOLDS = [{ days: 30, label: '30 d' }, { days: 60, label: '60 d' }, { days: 90, label: '90 d' }]

function filterByPeriod(items, period, key = 'date') {
  const now = new Date()
  return items.filter((item) => {
    const d = new Date(item[key])
    if (period === 'today') return d.toDateString() === now.toDateString()
    if (period === 'week')  return d >= new Date(now - 7 * 86400000)
    if (period === 'month') return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear()
    return true
  })
}

// ── Exportación Excel ─────────────────────────────────────────────────────────
function exportAnalytics(fSales, fExpenses, period) {
  // Hoja 1: Ventas (una fila por ítem de venta)
  const ventasRows = []
  fSales.forEach((s) => {
    if (s.status === 'VOIDED') return
    const fecha     = new Date(s.date).toLocaleDateString('es-CL')
    const canal     = CH_LABELS[s.channel ?? 'POS'] ?? s.channel
    const pago      = PAY_LABELS[s.paymentMethod] ?? s.paymentMethod ?? ''
    const totalBruto  = s.effectiveTotal ?? s.total ?? 0
    const iva         = Math.round(totalBruto * 19 / 119)
    const totalNeto   = totalBruto - iva
    const descuento   = s.discountAmount ?? 0
    const envCobro    = s.shipping?.cobro ?? 0
    const envCosto    = s.shipping?.costo ?? 0

    if (s.items?.length) {
      s.items.forEach((item) => {
        ventasRows.push({
          'Fecha':            fecha,
          'Canal':            canal,
          'Método de Pago':   pago,
          'Producto':         item.name ?? '',
          'Variante/Sabor':   item.variante ?? '',
          'Cantidad':         item.quantity ?? 1,
          'Precio Unitario':  item.price ?? 0,
          'Subtotal Ítem':    item.subtotal ?? (item.price * (item.quantity ?? 1)),
          'Costo Unitario':   item.cost ?? 0,
          'Descuento Venta':  descuento,
          'Total Bruto Venta': totalBruto,
          'IVA Venta':        iva,
          'Total Neto Venta': totalNeto,
          'Envío Cobrado':    envCobro,
          'Envío Costo':      envCosto,
          'Comisión Tarjeta': s.cardCommission ?? 0,
          'Estado':           s.status,
        })
      })
    } else {
      ventasRows.push({
        'Fecha': fecha, 'Canal': canal, 'Método de Pago': pago,
        'Producto': '', 'Variante/Sabor': '', 'Cantidad': 0,
        'Precio Unitario': 0, 'Subtotal Ítem': 0, 'Costo Unitario': 0,
        'Descuento Venta': descuento,
        'Total Bruto Venta': totalBruto, 'IVA Venta': iva, 'Total Neto Venta': totalNeto,
        'Envío Cobrado': envCobro, 'Envío Costo': envCosto,
        'Comisión Tarjeta': s.cardCommission ?? 0, 'Estado': s.status,
      })
    }
  })

  // Hoja 2: Gastos
  const gastosRows = fExpenses.map((e) => ({
    'Fecha':            e.date,
    'Descripción':      e.description,
    'Monto Total':      e.amount,
    'Neto':             Math.round(e.amount / 1.19),
    'IVA Crédito':      e.ivaCredito ?? 0,
    'Tipo':             e.type === 'variable' ? 'Variable' : 'Fijo',
    'Subtipo':          e.subtype ?? '',
    'Tipo Documento':   e.docType ?? '',
    'Auto-generado':    e.autoGenerated ? 'Sí' : 'No',
  }))

  const wsVentas = XLSX.utils.json_to_sheet(ventasRows)
  const wsGastos = XLSX.utils.json_to_sheet(gastosRows.length ? gastosRows : [{ 'Sin gastos': 'en el periodo' }])

  wsVentas['!cols'] = [
    { wch: 12 }, { wch: 16 }, { wch: 16 }, { wch: 28 }, { wch: 14 },
    { wch: 9  }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 },
    { wch: 16 }, { wch: 12 }, { wch: 14 }, { wch: 14 }, { wch: 12 },
    { wch: 16 }, { wch: 10 },
  ]
  wsGastos['!cols'] = [
    { wch: 12 }, { wch: 30 }, { wch: 14 }, { wch: 12 },
    { wch: 12 }, { wch: 10 }, { wch: 12 }, { wch: 14 }, { wch: 12 },
  ]

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, wsVentas, 'Ventas')
  XLSX.utils.book_append_sheet(wb, wsGastos, 'Gastos')

  const label = PERIODS.find((p) => p.key === period)?.label ?? period
  XLSX.writeFile(wb, `analiticas_${label}_${new Date().toISOString().slice(0, 10)}.xlsx`)
}

function BRow({ label, value, indent, separator, total, hide }) {
  if (hide) return null
  const isNeg = value < 0
  return (
    <tr className={[
      'brow',
      separator ? 'brow--sep'   : '',
      total     ? 'brow--total' : '',
      indent    ? 'brow--indent': '',
    ].filter(Boolean).join(' ')}>
      <td className="brow__label">{label}</td>
      <td className={`brow__value${isNeg ? ' brow__value--neg' : ''}${total ? ' brow__value--total' : ''}`}>
        {formatCLP(value)}
      </td>
    </tr>
  )
}

// ── Revenue Area Chart ────────────────────────────────────────────────────────
const MES_LABELS = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']

function compactCLP(v) {
  const abs = Math.abs(v)
  if (abs >= 1_000_000) return `$${(v / 1_000_000).toFixed(1)}M`
  if (abs >= 1_000)     return `$${(v / 1_000).toFixed(0)}K`
  return `$${Math.round(v)}`
}

function ChartTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null
  return (
    <div className="chart-tooltip">
      <p className="chart-tooltip__label">{label}</p>
      {payload.map((p) => (
        <div key={p.dataKey} className="chart-tooltip__row" style={{ color: p.color }}>
          <span>{p.name}</span>
          <span>{formatCLP(p.value)}</span>
        </div>
      ))}
    </div>
  )
}

function weekStartKey(dateStr) {
  // slice(0,10) handles both "YYYY-MM-DD" and "YYYY-MM-DDTHH:mm:ssZ" formats
  const d = new Date(dateStr.slice(0, 10) + 'T12:00:00')
  const day = d.getDay()
  d.setDate(d.getDate() - (day === 0 ? 6 : day - 1))
  return d.toISOString().slice(0, 10)
}

function RevenueChart({ sales, expenses, docs }) {
  const { data, granTitle, subtitle } = useMemo(() => {
    const allTs = [
      ...sales.map((s) => s.date),
      ...expenses.map((e) => e.date),
      ...(docs || []).map((d) => d.fechaEmision),
    ].filter(Boolean).map((s) => new Date(s).getTime()).filter((t) => !isNaN(t))

    if (allTs.length === 0) return { data: [], granTitle: 'TENDENCIA', subtitle: '' }

    const minTs   = Math.min(...allTs)
    const maxTs   = Math.max(...allTs)
    const spanDays = (maxTs - minTs) / 86400000

    // granularity thresholds
    const gran = spanDays <= 31 ? 'day' : spanDays <= 180 ? 'week' : spanDays <= 730 ? 'month' : 'year'

    function getKey(dateStr) {
      if (!dateStr) return null
      if (gran === 'day')   return dateStr.slice(0, 10)
      if (gran === 'week')  return weekStartKey(dateStr)
      if (gran === 'month') return dateStr.slice(0, 7)
      return dateStr.slice(0, 4)
    }

    function fmtLabel(key) {
      const d = new Date(key + 'T12:00:00')
      if (gran === 'day'  ) return `${d.getDate()} ${MES_LABELS[d.getMonth()]}`
      if (gran === 'week' ) return `${d.getDate()} ${MES_LABELS[d.getMonth()]}`
      if (gran === 'month') return MES_LABELS[parseInt(key.slice(5), 10) - 1]
      return key
    }

    const map = {}
    const ensure = (k) => { if (!map[k]) map[k] = { s: [], e: [], d: [] } }

    sales.filter((s) => s.status !== 'VOIDED').forEach((s) => {
      const k = getKey(s.date); if (!k) return; ensure(k); map[k].s.push(s)
    })
    expenses.forEach((e) => {
      const k = getKey(e.date); if (!k) return; ensure(k); map[k].e.push(e)
    })
    ;(docs || []).filter((d) => d.estado !== 'ANULADA').forEach((d) => {
      const k = getKey(d.fechaEmision); if (!k) return; ensure(k); map[k].d.push(d)
    })

    const chartData = Object.entries(map)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, { s, e, d }]) => {
        const m = calcAnalytics(s, e, d)
        return { mes: fmtLabel(key), ventasBrutas: m.ventasBrutas, gastos: m.gastosTotal, utilidadNeta: m.margenProductos }
      })

    const minD  = new Date(minTs)
    const maxD  = new Date(maxTs)
    const yMin  = minD.getFullYear()
    const yMax  = maxD.getFullYear()
    const range = yMin === yMax ? `${yMin}` : `${yMin} – ${yMax}`
    const granLabelMap = { day: 'por día', week: 'por semana', month: 'por mes', year: 'por año' }
    const titleMap     = { day: 'TENDENCIA DIARIA', week: 'TENDENCIA SEMANAL', month: 'TENDENCIA MENSUAL', year: 'TENDENCIA ANUAL' }

    return {
      data: chartData,
      granTitle: titleMap[gran],
      subtitle: `Ventas brutas · Gastos · Margen neto — ${range} (${granLabelMap[gran]})`,
    }
  }, [sales, expenses, docs])

  if (data.length === 0) return null

  return (
    <section className="analytics__card analytics__card--chart">
      <div className="chart-header">
        <div>
          <p className="analytics__card-title" style={{ marginBottom: 3 }}>{granTitle}</p>
          <p className="chart-subtitle">{subtitle}</p>
        </div>
        <div className="chart-legend">
          <span style={{ color: '#8b9ab5' }}>● Ventas Brutas</span>
          <span style={{ color: '#f97316' }}>● Gastos</span>
          <span style={{ color: '#0A84FF' }}>● Margen Neto</span>
        </div>
      </div>
      <ResponsiveContainer width="100%" height={240}>
        <AreaChart data={data} margin={{ top: 8, right: 4, left: 0, bottom: 0 }}>
          <defs>
            <linearGradient id="gVentas" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%"  stopColor="#8b9ab5" stopOpacity={0.28} />
              <stop offset="95%" stopColor="#8b9ab5" stopOpacity={0.02} />
            </linearGradient>
            <linearGradient id="gGastos" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%"  stopColor="#f97316" stopOpacity={0.28} />
              <stop offset="95%" stopColor="#f97316" stopOpacity={0.02} />
            </linearGradient>
            <linearGradient id="gUtilidad" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%"  stopColor="#0A84FF" stopOpacity={0.38} />
              <stop offset="95%" stopColor="#0A84FF" stopOpacity={0.02} />
            </linearGradient>
          </defs>
          <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" vertical={false} />
          <XAxis dataKey="mes" tick={{ fill: '#636366', fontSize: 11, fontFamily: 'inherit' }} axisLine={false} tickLine={false} />
          <YAxis tick={{ fill: '#636366', fontSize: 10, fontFamily: 'inherit' }} axisLine={false} tickLine={false} tickFormatter={compactCLP} width={56} />
          <Tooltip content={<ChartTooltip />} cursor={{ stroke: 'rgba(255,255,255,0.08)', strokeWidth: 1 }} />
          <Area type="monotone" dataKey="ventasBrutas" name="Ventas Brutas" stroke="#8b9ab5" strokeWidth={2} fill="url(#gVentas)"   dot={false} activeDot={{ r: 4, fill: '#8b9ab5', strokeWidth: 0 }} />
          <Area type="monotone" dataKey="gastos"       name="Gastos"        stroke="#f97316" strokeWidth={2} fill="url(#gGastos)"   dot={false} activeDot={{ r: 4, fill: '#f97316', strokeWidth: 0 }} />
          <Area type="monotone" dataKey="utilidadNeta" name="Margen Neto"   stroke="#0A84FF" strokeWidth={2} fill="url(#gUtilidad)" dot={false} activeDot={{ r: 4, fill: '#0A84FF', strokeWidth: 0 }} />
        </AreaChart>
      </ResponsiveContainer>
    </section>
  )
}

export function Analytics({ sales, expenses, products, docs = [] }) {
  const [period,       setPeriod]  = useState('month')
  const [stagnantDays, setStagnant] = useState(30)

  const fSales    = useMemo(() => filterByPeriod(sales,    period),                [sales,    period])
  const fExpenses = useMemo(() => filterByPeriod(expenses, period, 'date'),         [expenses, period])
  const fDocs     = useMemo(() => filterByPeriod(docs,     period, 'fechaEmision'), [docs,     period])
  const m         = useMemo(() => calcAnalytics(fSales, fExpenses, fDocs),          [fSales, fExpenses, fDocs])
  const capital   = useMemo(() => calcInventoryCapital(products ?? []),              [products])

  const trending = useMemo(() => {
    const map = {}
    fSales.forEach((sale) => {
      sale.items.forEach((item) => {
        if (!map[item.barcode]) map[item.barcode] = { barcode: item.barcode, name: item.name, qty: 0, revenue: 0 }
        map[item.barcode].qty     += (item.quantity ?? 1)
        map[item.barcode].revenue += (item.subtotal ?? (item.price * (item.quantity ?? 1)))
      })
    })
    return Object.values(map).sort((a, b) => b.qty - a.qty).slice(0, 10)
  }, [fSales])

  const stagnantProducts = useMemo(() => {
    const now = Date.now()
    const lastSaleMap = {}
    sales.forEach((sale) => {
      const t = new Date(sale.date).getTime()
      sale.items.forEach((item) => {
        if (!lastSaleMap[item.barcode] || t > lastSaleMap[item.barcode]) lastSaleMap[item.barcode] = t
      })
    })
    return (products ?? [])
      .map((p) => {
        const last      = lastSaleMap[p.barcode]
        const daysSince = last ? Math.floor((now - last) / 86400000) : null
        return { ...p, daysSince, neverSold: !last }
      })
      .filter((p) => p.neverSold || p.daysSince >= stagnantDays)
      .sort((a, b) => {
        if (a.neverSold !== b.neverSold) return a.neverSold ? -1 : 1
        return b.daysSince - a.daysSince
      })
      .slice(0, 15)
  }, [sales, products, stagnantDays])

  return (
    <div className="analytics">
      {/* Encabezado */}
      <div className="analytics__header">
        <div>
          <h2>Analiticas</h2>
          <p className="analytics__sub">
            {fSales.length} venta(s) retail · {m.countMayorista} doc(s) mayorista en el periodo
          </p>
        </div>
        <div className="analytics__header-right">
          <div className="period-tabs">
            {PERIODS.map(({ key, label }) => (
              <button key={key} onClick={() => setPeriod(key)} className={period === key ? 'active' : ''}>{label}</button>
            ))}
          </div>
          <button
            type="button"
            className="btn-export"
            onClick={() => exportAnalytics(fSales, fExpenses, period)}
            title="Exportar ventas y gastos del periodo a Excel"
          >
            ↓ Exportar Excel
          </button>
        </div>
      </div>

      {/* Gráfico de tendencia anual */}
      <RevenueChart sales={sales} expenses={expenses} docs={docs} />

      {/* Capital en inventario */}
      <section className="analytics__card analytics__card--capital">
        <p className="analytics__card-title">CAPITAL EN INVENTARIO</p>
        <p className="capital-value">{formatCLP(capital)}</p>
        <p className="capital-sub">Valor de stock al costo neto actual</p>
      </section>

      {/* Cascada financiera */}
      <section className="analytics__card">
        <h3 className="analytics__card-title">RESUMEN FINANCIERO</h3>
        <table className="breakdown">
          <tbody>
            <BRow label="Venta Bruta Total"              value={m.ventasBrutas}                                              />
            <BRow label="  · Retail (POS / E-Commerce)" value={m.ventasRetailBrutas}    indent hide={m.ventasMayoristaBrutas === 0} />
            <BRow label="  · Mayorista (Documentos)"    value={m.ventasMayoristaBrutas} indent hide={m.ventasMayoristaBrutas === 0} />
            <BRow label="IVA 19% (Debito Fiscal)"        value={-m.ivaTotalVentas}   indent separator />
            <BRow label="Venta Neta"                     value={m.ventasNetas}       />
            <BRow label="Costo de Productos"             value={-m.costoAdquisicion} indent separator />
            <BRow label="Margen Bruto Productos"         value={m.margenProductos}   />
            <BRow label="Cobro Envios (ingreso)"         value={m.ingresoEnvios}     indent hide={m.ingresoEnvios === 0 && m.costoEnvios === 0} />
            <BRow label="Costo Envios (gasto)"           value={-m.costoEnvios}      indent hide={m.ingresoEnvios === 0 && m.costoEnvios === 0} />
            <BRow label="Margen Logistico"               value={m.margenEnvios}      separator hide={m.ingresoEnvios === 0 && m.costoEnvios === 0} />
            <BRow label="Gastos Fijos y Variables"       value={-m.gastosBase}       indent />
            <BRow label="Comisiones Tarjeta"             value={-m.comisionesTargeta} indent hide={m.comisionesTargeta === 0} />
            <BRow label="UTILIDAD REAL"                  value={m.utilidadReal}      total />
          </tbody>
        </table>
      </section>

      {/* Declaración IVA */}
      <section className="analytics__card">
        <h3 className="analytics__card-title">DECLARACION IVA (ESTIMADA)</h3>
        <table className="breakdown">
          <tbody>
            <BRow label="Debito Fiscal (IVA ventas)"    value={m.debitoFiscal}   />
            <BRow label="Credito Fiscal (IVA facturas)" value={-m.creditoFiscal} indent separator />
            <BRow label="IVA POR PAGAR AL SII"          value={m.ivaPorPagar}    total />
          </tbody>
        </table>
        {m.creditoFiscal === 0 && (
          <p className="iva-tip">Registra gastos con documento FACTURA para acumular credito fiscal.</p>
        )}
      </section>

      {/* Canal + Método de pago */}
      <div className="analytics__grid-2">
        <section className="analytics__card">
          <h3 className="analytics__card-title">POR CANAL</h3>
          <table className="mini-table">
            <thead><tr><th>Canal</th><th>Ventas</th><th>Recibido</th></tr></thead>
            <tbody>
              {['POS', 'ECOM'].map((ch) => {
                const rows  = fSales.filter((s) => s.status !== 'VOIDED' && (s.channel ?? 'POS') === ch)
                const total = rows.reduce((a, s) => a + (s.effectiveTotal ?? s.total ?? 0), 0)
                return <tr key={ch}><td>{CH_LABELS[ch]}</td><td>{rows.length}</td><td>{formatCLP(total)}</td></tr>
              })}
              {m.countMayorista > 0 && (
                <tr>
                  <td><span className="sale-channel-badge sale-channel-badge--mayorista">Mayorista</span></td>
                  <td>{m.countMayorista}</td>
                  <td>{formatCLP(m.ventasMayoristaBrutas)}</td>
                </tr>
              )}
            </tbody>
          </table>
        </section>

        <section className="analytics__card">
          <h3 className="analytics__card-title">POR METODO DE PAGO</h3>
          <table className="mini-table">
            <thead><tr><th>Metodo</th><th>Ventas</th><th>Total</th></tr></thead>
            <tbody>
              {Object.entries(PAY_LABELS).map(([method, label]) => {
                const rows  = fSales.filter((s) => s.paymentMethod === method)
                const total = rows.reduce((a, s) => a + (s.effectiveTotal ?? s.total ?? 0), 0)
                if (rows.length === 0) return null
                return <tr key={method}><td>{label}</td><td>{rows.length}</td><td>{formatCLP(total)}</td></tr>
              })}
            </tbody>
          </table>
        </section>
      </div>

      {/* Tendencia */}
      <section className="analytics__card">
        <h3 className="analytics__card-title">TENDENCIA — MAS VENDIDOS</h3>
        <p className="analytics__card-sub">Periodo seleccionado · por unidades</p>
        {trending.length === 0 ? (
          <p className="empty-msg">Sin ventas en el periodo.</p>
        ) : (() => {
          const maxQty = trending[0].qty
          return (
            <div className="trend-list">
              {trending.map((p, i) => (
                <div key={p.barcode} className="trend-row">
                  <span className="trend-rank">#{i + 1}</span>
                  <div className="trend-info">
                    <span className="trend-name">{p.name}</span>
                    <div className="trend-bar-wrap">
                      <div className="trend-bar" style={{ width: `${(p.qty / maxQty) * 100}%` }} />
                    </div>
                  </div>
                  <span className="trend-qty">{p.qty} u</span>
                  <span className="trend-rev">{formatCLP(p.revenue)}</span>
                </div>
              ))}
            </div>
          )
        })()}
      </section>

      {/* Productos detenidos */}
      <section className="analytics__card">
        <div className="analytics__card-header-row">
          <div>
            <h3 className="analytics__card-title">PRODUCTOS DETENIDOS</h3>
            <p className="analytics__card-sub">Sin ventas en el historial completo</p>
          </div>
          <div className="period-tabs period-tabs--sm">
            {STAGNANT_THRESHOLDS.map(({ days, label }) => (
              <button key={days} onClick={() => setStagnant(days)} className={stagnantDays === days ? 'active' : ''}>
                {label}
              </button>
            ))}
          </div>
        </div>
        {stagnantProducts.length === 0 ? (
          <p className="empty-msg">Todos los productos se vendieron en este rango.</p>
        ) : (
          <table className="mini-table">
            <thead>
              <tr><th>Producto</th><th>Marca</th><th>Stock</th><th>Ultima Venta</th></tr>
            </thead>
            <tbody>
              {stagnantProducts.map((p) => (
                <tr key={p.barcode}>
                  <td>{p.name}{p.variante ? <span className="text-muted"> — {p.variante}</span> : ''}</td>
                  <td className="text-muted">{p.marca || '—'}</td>
                  <td>{p.stock ?? 0}</td>
                  <td>
                    {p.neverSold
                      ? <span className="stagnant-badge stagnant-badge--never">Sin ventas</span>
                      : <span className={`stagnant-badge ${p.daysSince >= 90 ? 'stagnant-badge--critical' : 'stagnant-badge--warn'}`}>
                          hace {p.daysSince} días
                        </span>
                    }
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>

      {/* Historial */}
      <section className="analytics__card">
        <h3 className="analytics__card-title">HISTORIAL DE VENTAS</h3>
        {fSales.length === 0 ? (
          <p className="empty-msg">Sin ventas en el periodo seleccionado.</p>
        ) : (
          <table className="mini-table">
            <thead>
              <tr><th>Fecha</th><th>Canal</th><th>Items</th><th>Recibido</th><th>Pago</th><th>Envio</th></tr>
            </thead>
            <tbody>
              {[...fSales].reverse().slice(0, 100).map((s) => (
                <tr key={s.id}>
                  <td>{new Date(s.date).toLocaleString('es-CL', { dateStyle: 'short', timeStyle: 'short' })}</td>
                  <td>{CH_LABELS[s.channel ?? 'POS']}</td>
                  <td>{s.items.reduce((a, i) => a + i.quantity, 0)}</td>
                  <td>{formatCLP(s.effectiveTotal ?? s.total)}</td>
                  <td>{PAY_LABELS[s.paymentMethod] ?? s.paymentMethod}</td>
                  <td>{s.shipping?.cobro || s.shipping?.costo ? `${formatCLP(s.shipping.cobro)} / ${formatCLP(s.shipping.costo)}` : '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </div>
  )
}